### ISSUE TITLE
partitioning feature

### ISSUE THREAD

**Issue by vkudyushev** [dgzlopes/python-liftbridge#9]
Hello! I've not found some mention about creating multi partition stream in source code and examples. Does it implemented in your lib?

**Comment by LaPetiteSouris** [comment]
Unfortunately, to date  it is not implemented. It is in the plan. 

However, I am thinking [this](https://github.com/dgzlopes/python-liftbridge/issues/6) should be dealt with first, as multiple partition and multi replication will have effect , as described in the issue [#6 ].

Helps are welcomed.

**Comment by vkudyushev** [comment]
I've already implemented it is just now, for stream creation and messages reading) It wasn't so hard, but not fully tested.

**Comment by LaPetiteSouris** [comment]
> I've already implemented it is just now, for stream creation and messages reading) It wasn't so hard, but not fully tested.

In that case, would you mind create a PR ? For the test, as of now, we don't have unit or integration tests. Manual test seems to be the only way for now

**Comment by vkudyushev** [comment]
I've just tested sending and receiving messages via several partitions and it seems work. Now will try to create a PR.

**Comment by vkudyushev** [comment]
@LaPetiteSouris check it!
P.S.: I'm also interesting in async client, but PB API seems to be only sync and it can be a problem to create full async client...

**Comment by dgzlopes** [comment]
If I remember correctly there are some Python async based gRPC clients... Maybe this [issue](https://github.com/grpc/grpc/issues/16329) is useful!

**Comment by vkudyushev** [comment]
OK, thnx!
So, as I understand, all clients (and Golang too) communicates with server via rpc protocol? Seems like it's not the fastest way...

**Comment by dgzlopes** [comment]
Yep, we use [gRPC](https://grpc.io/). About performance... Well, It depends on what you want to do. 

I'm sure @tylertreat can give you better insights about the current performance. You can ask in [Slack](https://github.com/liftbridge-io/liftbridge#community)

**Comment by dgzlopes** [comment]
If you want some general gRPC benchmarks (per language), they are available on the official website.

**Comment by vkudyushev** [comment]
> Well, It depends on what you want to do.

10-15 partitions with 1000 to 5000 messages (summary to all, not to every) in 1 minute, each message up to 100Kb (some topic messages <1Kb, some topics always greater than 50Kb). each consumer on a separate server, producer on a separate server and nats with liftbridge has own server. what do you think?

**Comment by LaPetiteSouris** [comment]
> @LaPetiteSouris check it!
> P.S.: I'm also interesting in async client, but PB API seems to be only sync and it can be a problem to create full async client...

It seems that Async Publish is in the [roadmap](https://github.com/liftbridge-io/liftbridge/blob/master/documentation/roadmap.md#asynchronous-publish-api-215)

**Comment by vkudyushev** [comment]
> It seems that Async Publish is in the [roadmap](https://github.com/liftbridge-io/liftbridge/blob/master/documentation/roadmap.md#asynchronous-publish-api-215)

good news!

**Comment by tylertreat** [comment]
Yes, the async publish API is getting close to being merged and will be included in Liftbridge 1.2.0. This will allow for _much_ higher throughput.

**Comment by LaPetiteSouris** [comment]
Close by #10
